git clone https://github.com/kingazcore/mod-transmog.git
git clone https://github.com/kingazcore/mod-anticheat.git
git clone https://github.com/kingazcore/mod-eluna.git
git clone https://github.com/kingazcore/mod-morphsummon.git
git clone https://github.com/kingazcore/mod-dynamic-xp.git
git clone https://github.com/kingazcore/mod-random-enchants
git clone https://github.com/kingazcore/mod-ah-bot.git
git clone https://github.com/kingazcore/mod-learn-spells.git
git clone https://github.com/kingazcore/mod-solo-lfg.git
git clone https://github.com/kingazcore/mod-multi-client-check.git
git clone https://github.com/kingazcore/mod-duel-reset
git clone https://github.com/kingazcore/mod-world-chat
git clone https://github.com/kingazcore/mod-1v1-arena.git
git clone https://github.com/kingazcore/mod-reward-shop.git
git clone https://github.com/kingazcore/mod-cfbg
git clone https://github.com/kingazcore/mod-bg-item-reward.git
git clone https://github.com/kingazcore/mod-skip-dk-starting-area.git
git clone https://github.com/kingazcore/mod-autobalance.git
git clone https://github.com/azerothcore/mod-npc-enchanter
git clone https://github.com/azerothcore/mod-npc-services